---
title: "Flow Diagram"
author: "Matthew Hoctor, Bryon Langford"
date: "7/4/2021"
output:
  html_document:
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (Sys.info()["sysname"] == "Windows") 
  knitr::opts_chunk$set(engine.path = list(stata = "C:/Program Files/Stata17/StataBE-64")) 
if ((Sys.info()["sysname"] == "Darwin"))
  knitr::opts_chunk$set(engine.path = list(stata = "/Applications/Stata/StataIC"))
```

```{r libraries, include=FALSE}
#library(dplyr)
#library(readxl)
#library(tidyverse)
#library(ggplot2)
#library(CarletonStats)
#library(pwr)
#library(BSDA)
#library(exact2x2)
#library(car)
#library(dvmisc)
#library(emmeans)
#library(gridExtra)
#library(DescTools)
#library(epitools)
#library(pROC)
#library(rje)
#library(lmtest)
#library(gtsummary)
#library(mfp)
#library(linearspline)
#library(dagitty)
library(DiagrammeR)
#library(metagear)
# library(Gmisc, quietly = FALSE)
# library(glue)
# library(htmlTable)
# library(grid)
# library(magrittr)
library(Statamarkdown)
```

# Data for Flow Diagram

```{stata}
use "data\NHANES0518_new.dta", clear

ta MEC_response
ta BP_miss MEC_response

ta MJ_miss BP_miss if MEC_response==1

ta AGE_exclude if BP_miss==0 & MJ_miss==0

ta AGE_exclude
ta AGE_exclude BP_miss
ta BP_miss MJ_miss if AGE_exclude==0


ta BP_miss MJ_miss if AGE_exclude==0 & gndr==0
ta BP_miss MJ_miss if AGE_exclude==0 & gndr==1
```


# New Flow Diagram

```{r}
# Define some sample data
data <- list(a=59842 , b=42674, c=19811, d=18510, e=9353, f=9157)

DiagrammeR::grViz("
digraph rmarkdown{

# Box
node [shape = box]

A;

A[label = 
    <
    Missing blood pressure data:<br ALIGN = 'LEFT'/> 
    &#8226; No mobile examination center exam<br ALIGN = 'LEFT'/> 
    (n = 2428)<br ALIGN = 'LEFT'/> 
    &#8226; Insufficient BP data for AHA/ACC<br ALIGN = 'LEFT'/>
    classification (n = 14740)<br ALIGN = 'LEFT'/>
    >
]

B;

B[label = 
    <
    Missing cannabis use data<br ALIGN = 'LEFT'/> 
    (n = 22863)<br ALIGN = 'LEFT'/>
    >
]

C;

C[label = 
    <
    Outside of age range 20-69 years<br ALIGN = 'LEFT'/> 
    (n = 1301)<br ALIGN = 'LEFT'/>
    >
]

a [label = '@@1']
a1 [shape = point width = 0.01]
b [label = '@@2']
b1 [shape = point width = 0.01]
c [label = '@@3']
c1 [shape = point width = 0.01]
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']


a -> a1 [arrowhead = none]
a1 -> A
a1 -> b 
b -> b1 [arrowhead = none]
b1 -> B
b1 -> c
c -> c1 [arrowhead = none]
c1 -> C
c1 -> d -> e
d -> f

{rank=same; a1 A}
{rank=same; b1 B}
{rank=same; c1 C}

}

[1]: paste0('NHANES 2007-2018 (n = ', data$a, ')')
[2]: paste0('Sufficient BP data (n = ', data$b, ')')
[3]: paste0('Sufficient exposure and outcome data (n = ', data$c, ')')
[4]: paste0('Adults age 20-69 with BP data & cannabis use data (n = ', data$d, ')')
[5]: paste0('Women (n = ', data$e, ')')
[6]: paste0('Men (n = ', data$f, ')')
")
```

# Old Flow Diagram

```{r}
# Define some sample data
data <- list(a=59842 , b=28721, c=26046, d=18510, e=9353, f=9157)

DiagrammeR::grViz("
digraph graph2 {

graph [layout = dot]

# node definitions with substituted label text
node [shape = rectangle, width = 4, fillcolor = Biege]
a [label = '@@1']
a1 [shape = point width = 0.01]
a2 [label = 'Missing BP data\nNo mobile examination center exam\nInsufficient BP data for AHA/ACC clasification' align = right]
b [label = '@@2']
c [label = '@@3']
d [label = '@@4']
e [label = '@@5']
f [label = '@@6']

a -> a1 [arrowhead = none]
a1 -> b -> c -> d -> e
a1 -> a2
d -> f

{rank=same; a1 a2}

}

[1]: paste0('NHANES 2007-2018 (n = ', data$a, ')')
[2]: paste0('Adults age 20-69 (n = ', data$b, ')')
[3]: paste0('Adults age 20-69 with BP data (n = ', data$c, ')')
[4]: paste0('Adults age 20-69 with BP data & cannabis use data (n = ', data$d, ')')
[5]: paste0('Women (n = ', data$e, ')')
[6]: paste0('Men (n = ', data$f, ')')
")
```

