---
title: "Model Building"
author: "Bryon Langford, Matthew Hoctor"
date: "7/21/2021"
output:
  html_document:
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (Sys.info()["sysname"] == "Windows") 
  knitr::opts_chunk$set(engine.path = list(stata = "C:/Program Files/Stata17/StataBE-64")) 
if ((Sys.info()["sysname"] == "Darwin"))
  knitr::opts_chunk$set(engine.path = list(stata = "/Applications/Stata/StataIC"))
```

```{r libraries, include=FALSE}
library(Statamarkdown)
```

Model Building by Deletion

# Full Model

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1): logit BP_cat i.MJ gndr i.EDUC_cat i.race_eth i.SMK_cat i.AL_cat bmxbmi hei2015 indfmpir ridageyr, or
```

# Deletion Cycle 1

## Education

## Race/Ethnicity

## Smoking

## 

# Deletion Cycle 2
