---
title: "Table 3 Calculations"
author: "Bryon Langford, Matthew Hoctor"
date: "7/21/2021"
output:
  html_document:
    number_sections: no
    theme: lumen
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: no
  pdf_document:
    toc: yes
  word_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

if (Sys.info()["sysname"] == "Windows") 
  knitr::opts_chunk$set(engine.path = list(stata = "C:/Program Files/Stata17/StataBE-64")) 
if ((Sys.info()["sysname"] == "Darwin"))
  knitr::opts_chunk$set(engine.path = list(stata = "/Applications/Stata/StataIC"))
```

```{r libraries, include=FALSE}
library(Statamarkdown)
```


# Model 1: Crude

## Women

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ, or
```

## Men

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ, or
```

# Model 2: adjusting for confounders

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1): logit BP_cat i.MJ gndr ridageyr, or
```

## Women

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ gndr ridageyr, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ gndr ridageyr, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ gndr ridageyr, or
```

## Men

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ gndr ridageyr, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ gndr ridageyr, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ gndr ridageyr, or
```

# Model 3: fully adjusted (including mediators)

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1): logit BP_cat i.MJ gndr i.AL_cat bmxbmi ridageyr, or
```

## Women

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==0 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

## Men

### Elevated BP

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==1)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

### Stage 1 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==2)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

### Stage 2 HTN

```{stata}
use "data\NHANES0518_new.dta", clear
svyset sdmvpsu [pw=wtmec12yr], strata(sdmvstra)

xi: svy,subpop(if include==1 & gndr==1 & (BP_cat==0 | BP_cat==3)): logit BP_cat i.MJ gndr ridageyr i.AL_cat bmxbmi, or
```

